# Generated by Django 3.1.1 on 2023-06-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_hospital_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
    ]
