# Generated by Django 3.1.1 on 2023-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_hospital_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ambulance_contacts',
            field=models.CharField(default='no ambulance contact', max_length=50000),
        ),
    ]
