# Generated by Django 3.1.1 on 2023-06-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230619_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
    ]
