# Generated by Django 5.0.2 on 2024-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_hospital_accepted_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_appointments',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals_worked',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='medicalstaff',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='paymentservice',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='accepted_paymentservices',
        ),
        migrations.RemoveField(
            model_name='serviceprovided',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='service_provided',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='accepted_insurance',
            field=models.CharField(default='No insurances accepted', max_length=5000),
        ),
        migrations.AddField(
            model_name='hospital',
            name='general_services',
            field=models.ManyToManyField(related_name='hospitals', to='store.generalservice'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='HospitalService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='MedicalStaff',
        ),
        migrations.DeleteModel(
            name='PaymentService',
        ),
        migrations.DeleteModel(
            name='ServiceProvided',
        ),
    ]
