# Generated by Django 5.0.2 on 2024-03-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_specializedcare_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializedcare',
            name='available_times',
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('specialized_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.specializedcare')),
            ],
        ),
    ]
