# Generated by Django 5.0.2 on 2024-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_specializedcare_available_times_availabletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
