# Generated by Django 5.0.2 on 2024-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_availabletime_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedcare',
            name='booking_available',
            field=models.BooleanField(default=True),
        ),
    ]
