# Generated by Django 5.0.2 on 2024-03-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_specializedcare_booking_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
