# Generated by Django 5.0.2 on 2024-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
