# Generated by Django 5.0.2 on 2024-03-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_appointment_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
