# Generated by Django 5.0.2 on 2024-03-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='hospital',
            field=models.ForeignKey(default='ffea3154-ed09-4d89-a7a6-de74ee5a1742', on_delete=django.db.models.deletion.CASCADE, to='store.hospital'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.TextField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.availabletime')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hospital')),
                ('specialized_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.specializedcare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
