# Generated by Django 5.0.2 on 2024-03-06 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_email_appointment_hospital_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_email', models.EmailField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.availabletime')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hospital')),
                ('specialized_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.specializedcare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
