# Generated by Django 3.2 on 2024-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_consultationtypes_doctorhomecareavailabletime_doctortelemedicineavailabletime_isdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='isdoctor',
            name='licensing_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isdoctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isdoctor',
            name='hospital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isdoctor',
            name='specialty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
