# Generated by Django 3.2 on 2024-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20240422_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortelemedicineavailabletime',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctortelemedicineavailabletime',
            name='time',
            field=models.TimeField(),
        ),
    ]
