# Generated by Django 3.1.1 on 2024-11-11 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0025_auto_20240515_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_plate', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=5000)),
                ('phone_number', models.CharField(default='no phone number', max_length=200)),
                ('vehicle_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='specialized_care',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsultationTypes',
        ),
        migrations.RemoveField(
            model_name='doctorhomecareavailabletime',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctortelemedicineavailabletime',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='general_services',
        ),
        migrations.RemoveField(
            model_name='isdoctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specializedcare',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='specializedcare',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='specialized_care',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='hospital_email',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='specialized_care',
        ),
        migrations.RemoveField(
            model_name='successfulappointment',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorHomeCareAvailableTime',
        ),
        migrations.DeleteModel(
            name='DoctorTelemedicineAvailableTime',
        ),
        migrations.DeleteModel(
            name='GeneralService',
        ),
        migrations.DeleteModel(
            name='IsDoctor',
        ),
        migrations.DeleteModel(
            name='SpecializedCare',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='available_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.availabletime'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vehicle'),
        ),
        migrations.AddField(
            model_name='successfulappointment',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='hospital',
            field=models.ForeignKey(default='ffea3154-ed09-4d89-a7a6-de74ee5a1742', on_delete=django.db.models.deletion.CASCADE, to='store.vehicle'),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
