# Generated by Django 3.1.1 on 2024-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20241111_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_available',
            field=models.BooleanField(default=True),
        ),
    ]
