# Generated by Django 3.1.1 on 2024-11-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_vehiclemaintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='driver',
        ),
    ]
