# Generated by Django 3.1.1 on 2024-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20241111_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='maintenance_done',
            field=models.BooleanField(default=False),
        ),
    ]
