# Generated by Django 3.1.1 on 2024-11-11 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0031_vehiclemaintenance_maintenance_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleinspection',
            options={'verbose_name': 'Vehicle Inspection', 'verbose_name_plural': 'Vehicle Inspections'},
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='note',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='driver',
            field=models.ForeignKey(default=1, limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='inspection_done',
            field=models.BooleanField(default=False),
        ),
    ]
