# Generated by Django 3.1.1 on 2024-11-12 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0034_auto_20241111_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rides', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
