# Generated by Django 3.1.1 on 2024-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_ride_destination_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_km', models.DecimalField(decimal_places=2, help_text='Cost per kilometer', max_digits=10)),
                ('promotional_message', models.TextField(blank=True, help_text='Promotional message related to cost management', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
