# Generated by Django 3.2 on 2024-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_doc',
            field=models.BooleanField(default=False),
        ),
    ]
