# Generated by Django 3.2 on 2024-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='specialty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
