# Generated by Django 3.2 on 2024-04-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='specialty',
        ),
    ]
