# Generated by Django 3.1.1 on 2024-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_docprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='field',
        ),
    ]
