# Generated by Django 3.1.1 on 2024-11-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_docprofile_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocProfile',
            new_name='DriverProfile',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_doc',
            new_name='is_driver',
        ),
    ]
